[DEFAULT]
# All sections below are required unless otherwise specified.
# See https://github.com/fastai/nbdev/blob/master/settings.ini for examples.

### Python library ###
repo = PhysioJEPA
lib_name = %(repo)s
version = 0.0.1
min_python = 3.9
license = apache2
black_formatting = False

### nbdev ###
doc_path = _docs
lib_path = physiojepa
nbs_path = nbs
recursive = True
tst_flags = notest
put_version_in_init = True

### Docs ###
branch = main
custom_sidebar = False
doc_host = https://%(user)s.github.io
doc_baseurl = /%(repo)s
git_url = https://github.com/%(user)s/%(repo)s
title = %(lib_name)s

### PyPI ###
audience = Developers
author = benmfox
author_email = benmfox@me.com
copyright = 2023 onwards, %(author)s
description = PhysioJEPA
keywords = nbdev jupyter notebook python
language = English
status = 3
user = benmfox

### Optional ###
requirements = optuna==3.6.1 optuna-integration wandb==0.19.2 scikit-learn ipykernel pyedflib mne edfio lxml nbdev==2.3.29 tqdm scipy zarr dask psycopg torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 torchmetrics==1.4.0 seaborn matplotlib psycopg[binary] pyyaml numpy pandas streamlit plotly==5.15.0 plotly_resampler lightning==2.4.0 pytorch_metric_learning
# dev_requirements = 
# console_scripts =