"""Im lost too."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_loss.ipynb.

# %% auto #0
__all__ = ['mse_loss', 'mae_loss', 'mape', 'cosine_similarity_loss', 'huber_loss', 'smoothl1_loss', 'mse_variance_loss',
           'CrossEntropyLoss', 'FocalLoss']

# %% ../nbs/07_loss.ipynb #662753a7
import torch, numpy as np, torch.nn.functional as F, torch.nn as nn

# %% ../nbs/07_loss.ipynb #3de81584
def mse_loss(preds, target):
    """
    preds:   [bs x num_patch x n_vars x patch_len]
    targets: [bs x num_patch x n_vars x patch_len] 
    """
    return F.mse_loss(preds, target, reduction='mean')

def mae_loss(preds, target):
    """
    preds:   [bs x num_patch x n_vars x patch_len]
    targets: [bs x num_patch x n_vars x patch_len] 
    """
    return F.l1_loss(preds, target, reduction='mean')


def mape(preds, target):
    epsilon = np.finfo(np.float64).eps # from sklearn
    return (((target - preds).mean(dim=-1).abs()) / (target.mean(dim=-1).abs()).clƒamp(min=epsilon)).sum()
    

def cosine_similarity_loss(preds,target):
    """
    preds:   [bs x num_patch x n_vars x patch_len]
    targets: [bs x num_patch x n_vars x patch_len] 
    """
    sim = F.cosine_similarity(preds,target, dim=-1)
    n_elements = torch.numel(preds)
    sim = sim.sum() / torch.as_tensor(n_elements, device=preds.device)
    return -sim

def huber_loss(preds, target, delta=1):
    """
    preds:   [bs x num_patch x n_vars x patch_len]
    targets: [bs x num_patch x n_vars x patch_len] 
    """ 
    return F.huber_loss(preds, target, delta=delta, reduction='mean')
    

def smoothl1_loss(preds, target):
    return F.smooth_l1_loss(preds, target, reduction='mean')

def mse_variance_loss(preds, target, representations, alpha = 0.2):
    """
    preds:   [bs x num_patch x n_vars x patch_len]
    targets: [bs x num_patch x n_vars x patch_len] 
    representations: [bs x nvars x d_model x num_patch]
    """
    loss = 0.0
    for pred_i, target_i, representations_i in zip(preds, target, representations):
        loss = loss + F.mse_loss(pred_i, target_i, reduction='mean')
        loss = loss + alpha * F.relu(1.0 - representations_i.std(dim=-1)).mean()
    loss /= len(preds)
    return loss


# %% ../nbs/07_loss.ipynb #8fdb2a2d
class CrossEntropyLoss(nn.Module):
    """
    Cross entropy loss with ignore_index.
    """
    def __init__(self, ignore_index=-100, reduction='mean', weight=None, label_smoothing=0, soft_labels=False):
        super().__init__()
        self.ignore_index = ignore_index
        self.reduction = reduction
        self.label_smoothing = label_smoothing
        self.weight = weight
        if weight is not None:
            self.weight = weight.float()
        if soft_labels:
            # this has to be -100 for CE to work with soft labels
            ignore_index = -100
        self.soft_labels = soft_labels
        self.loss = nn.CrossEntropyLoss(ignore_index=ignore_index, reduction='none', weight=self.weight, label_smoothing=label_smoothing)
    
    def forward(self, x, y):
        """
        x: [bs x n classes x n patches]
        y: [bs x n patches] or [bs x n classes x n patches]
        """
       
        loss = self.loss(x, y)
        if self.soft_labels and y.dim() == 3:
            mask = y.sum(dim=1, keepdim=True) > 0  # [bs x 1 x soft_labels]
            loss = loss * mask
            loss = loss.sum() / mask.sum().clamp(min=1e-6) if self.reduction == 'mean' else loss.sum()
        else:
            mask = y != self.ignore_index
            loss = loss * mask
            loss = loss.sum() / mask.sum().clamp(min=1e-6) if self.reduction == 'mean' else loss.sum()
        return loss


# %% ../nbs/07_loss.ipynb #1a39f76d
class FocalLoss(nn.Module):
    """
    adapted from tsai, weighted multiclass focal loss
    https://github.com/timeseriesAI/tsai/blob/bdff96cc8c4c8ea55bc20d7cffd6a72e402f4cb2/tsai/losses.py#L116C1-L140C20
    """
    def __init__(self, 
                 weight=None, 
                 gamma=2., 
                 reduction='mean',
                 ignore_index=-100
                 ):
        super().__init__()
        self.weight = weight
        self.gamma = gamma
        self.reduction = reduction
        self.ignore_index = ignore_index
    
    __name__ = 'focalloss'
        
    def forward(self, x, y):
        """
        x: [bs x n classes x n patches]
        y: [bs x n patches]
        """
        bs = x.size(0)

        if x.dim() == 3:
            x = x.permute(0,2,1) # bs x n_patches x n_classes
            x = x.reshape(-1, x.size(-1)) # bs * n_patches x n_classes

        log_prob = F.log_softmax(x, dim=-1)
        weight = self.weight.float().to(x.device) if self.weight is not None else None
        if y.dim() == 2:
            # hard labels
            y = y.flatten(start_dim=-2) # bs * num_patches
            valid_mask = y != self.ignore_index
            valid_y = y[valid_mask]
            valid_log_prob = log_prob[valid_mask]
            pt = valid_log_prob[torch.arange(len(valid_y)), valid_y].exp()
            ce = F.nll_loss(valid_log_prob, valid_y, weight=weight, reduction='none', ignore_index=self.ignore_index)
            loss = (1 - pt) ** self.gamma * ce
            loss = loss.sum() / valid_mask.sum().clamp(min=1e-5) if self.reduction == 'mean' else loss.sum()
        else:  # soft labels
            y = y.permute(0,2,1) # bs x n patches x n classes
            mask = (y.sum(dim=2) > 0).float() # bs x n patches
            mask = mask.flatten(start_dim=-2) # bs * n_patches
            y = y.reshape(-1, y.size(-1)) # bs * n_patches x n_classes

            if weight is not None:
                ce = -(y * log_prob * weight).sum(dim=-1) # bs * n_patches
            else:
                ce = -(y * log_prob).sum(dim=-1) # bs * n_patches
            pt = (y * log_prob.exp()).sum(dim=-1).clamp(min=1e-7, max=1)
            loss = (1 - pt) ** self.gamma * ce
            # Positions to ignore will have all zeros
            loss = loss * mask
            loss = loss.sum() / mask.sum().clamp(min=1e-5) if self.reduction == 'mean' else loss.sum()
        return loss
