# JEPA Patch Training Configuration - Hypotension Project

run_config:
  model_type: 'JEPA'
  wandb_project: "Bedside Hypotension JEPA"
  model_run: "1"
  name: "JEPA_II_PLETH_ABP_all"
  random_state: 12
  precision: "32"
  test_n_samples: 0

# Data Paths
paths:
  data_dir: "zarr_store/allzarr/"
  models_dir: "models/"
  outcome_df_path: 'hypotension_labels_mimic_all_events_rolling5min.csv.gz'
  dataset_filename: "125Hz_ABPIIPLETHchannels_1800sec_segment_1800sec_stride_all"


# Dataset Configuration
dataset:
  channels: ['ABP', 'II', 'PLETH']
  frequency: 125
  patch_seconds: 1 
  overlap: 0.0
  seq_len_sec: 1800  # 30 minutes
  sample_stride_sec: 1800  # 30 minutes
  max_seq_len_sec: 1800
  min_seq_len_sec: 1800
  constant_nan_tolerance: 0.2
  use_transforms: false
  normalize_signals: true
  require_all_channels: true
  y_outcome: "hypotension_label"

# Model Architecture
encoder:
  d_model: 512
  nhead: 8
  num_layers: 3
  pe_type: "rotary"
  mlp_ratio: 4.0
  use_tst_block: true
  shared_embedding: false
  qkv_bias: true
  qk_scale: null
  drop_rate: 0.1
  attn_drop_rate: 0.
  jepa: true
  tokenizer_type: "simple"
  tokenizer_kwargs:
    depth: 1 
    bottleneck_channels: 112 # 16 * 7
    residual: true # residual doesnt run when c in is 1
    kernel_size: 40
    bottleneck: true # there is no bottleneck if in channels is 1

predictor:
  predictor_embed_dim: 128
  nhead: 4
  num_layers: 2
  use_tst_block: true
  pe_type: "rotary"
  mlp_ratio: 4.0
  qkv_bias: true
  qk_scale: null
  drop_rate: 0.1
  attn_drop_rate: 0.
  c_in_mask_tokens: 3 # number of channels in the encoder (if treating channels sep)

# Training Configuration
training:
  n_gpus: 2 
  batch_size: 128
  epochs: 100
  num_workers: 14 # leave 2 for other processes
  accumulate_grad_batches: 1
  huber_delta: 1
  target_mask_range: [0.1, 0.3]
  context_mask_range: [0.1, 0.4]
  mask_block_range: [1, 1] # not implemented
  ema_decay: 0.996
  val_check_interval: 1.0
  use_gradient_clipping: true
  gradient_clip_val: 1.
  gradient_clip_algorithm: "norm"
  use_lr_finder: false
  loss_fxn: "mse"

optimizer:
  learning_rate: 0.00001
  weight_decay: 0.04
  use_weight_decay_scheduler: true
  final_weight_decay: 0.4
  optimizer_type: "adamw"

# OneCycle Scheduler Parameters
scheduler:
  scheduler_type: "onecycle"
  max_lr: 0.0006
  div_factor: 25
  final_div_factor: 100
  pct_start: 0.3
  anneal_strategy: "cos"